import type { NextPage } from 'next';
import Head from 'next/head';
import MetaMaskCard from '../components/ConnectorCard/MetaMask.Card';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/bitcoin.svg" />
      </Head>
      <div className='flex flex-row flex-wrap justify-center items-center'>
        <MetaMaskCard />
      </div>
    </div>
  )
}

export default Home
